### ISSUE TITLE
Not getting predictions 

### ISSUE THREAD

**Issue by KonstantinosTro** [udacity/AIND-VUI-Capstone#4]
Hello I am trying to replicate the code and everything is working fine with no error but when I try to run get_predictions function I get an empty predicted transcription any ideas what is happening? bellow is the output:

Layer (type)                 Output Shape              Param #   
=================================================================
the_input (InputLayer)       (None, None, 13)          0         
_________________________________________________________________
rnn (GRU)                    (None, None, 29)          3741      
_________________________________________________________________
softmax (Activation)         (None, None, 29)          0         
=================================================================
Total params: 3,741
Trainable params: 3,741
Non-trainable params: 0
_________________________________________________________________
None
--------------------------------------------------------------------------------
True transcription:

mister quilter is the apostle of the middle classes and we are glad to welcome his gospel
--------------------------------------------------------------------------------
Predicted transcription:

--------------------------------------------------------------------------------

**Comment by NeoBoy** [comment]
Same is happening with me. Suggestions requested!

**Comment by NeoBoy** [comment]
>           Same is happening with me. Suggestions requested!

I m using model_0 while input features are selected as Spectrogram

**Comment by KonstantinosTro** [comment]
you should use models except 0 models 0 justs learns the space character and nothing else

**Comment by NeoBoy** [comment]
Thanks for the clarification.
