### ISSUE TITLE
how adding the accuracy ? 

### ISSUE THREAD

**Issue by ghanou0095** [udacity/AIND-VUI-Capstone#5]
hello , i tried to modify this code to add other models ( architectures), now i want that the results display to me the accuracy ( WER word error rate , or the CER caractere error rate ) to be able to evaluate if my architecture is good or not !! thank you very much

**Comment by ronny-udacity** [comment]
Hope this StackOverview post is useful - [Tensorflow Callback as Custom Metric for CTC](https://stackoverflow.com/questions/60285167/tensorflow-callback-as-custom-metric-for-ctc)
